apiVersion: apps/v1
kind: Deployment
metadata:
 name: laravel-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: laravel
 template:
  metadata:
   labels:
    app: laravel
  spec:
   containers:
    - name: laravel
      image: docker.io/leduccuong01/egiwork-web-v1:2.0.0
      ports:
      - containerPort: 8000
        name: laravel
        