apiVersion: v1
kind: Service
metadata:
  name: egiwork-phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
  - name: phpmyadmin
    port: 80
    targetPort: 80
    nodePort: 30307
  type: NodePort