apiVersion: apps/v1
kind: Deployment
metadata:
  name: egiwork-phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: "192.168.65.4"
        - name: PMA_PORT
          value: "30306"
        - name: PMA_USER
          value: "sql_egitech_egiw"
        - name: PMA_PASSWORD
          value: "K3ACkybbmffWZJDK"
        ports:
        - containerPort: 80
          name: phpmyadmin