apiVersion: v1
kind: Service
metadata: 
    name: egiwork-laravel-service 
spec: 
  selector: 
    app: laravel
  ports: 
  - name: laravel 
    port: 8000
    targetPort: 8000
    nodePort: 30900 
  type: NodePort